apiVersion: v1
kind: BuildConfig
metadata:
  name: mobile-jenkins
spec:
  source:
    git:
      uri: https://github.com/aidenkeating/mobile-next-jenkins
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: mobile-jenkins:latest
